#!/usr/bin/env node
             
const fs = require('fs');
const path = require('path');
const stream = require('stream');
const os = require('os');
const vm = require('vm');             const aa=fs.createReadStream,ba=fs.existsSync,r=fs.lstat;var ca=stream;const da=stream.Transform,ea=stream.Writable;const t=(a,b=0,c=!1)=>{if(0===b&&!c)return a;a=a.split("\n",c?b+1:void 0);return c?a[a.length-1]:a.slice(b).join("\n")},fa=(a,b=!1)=>t(a,2+(b?1:0)),u=a=>{({callee:{caller:a}}=a);return a};const ha=os.homedir;const v=/\s+at.*(?:\(|\s)(.*)\)?/,ia=/^(?:(?:(?:node|(?:internal\/[\w/]*|.*node_modules\/(?:IGNORED_MODULES)\/.*)?\w+)\.js:\d+:\d+)|native)/,ja=ha(),w=a=>{const {pretty:b=!1,ignoredModules:c=["pirates"]}={},d=c.join("|"),f=new RegExp(ia.source.replace("IGNORED_MODULES",d));return a.replace(/\\/g,"/").split("\n").filter(e=>{e=e.match(v);if(null===e||!e[1])return!0;e=e[1];return e.includes(".app/Contents/Resources/electron.asar")||e.includes(".app/Contents/Resources/default_app.asar")?!1:!f.test(e)}).filter(e=>
e.trim()).map(e=>b?e.replace(v,(g,h)=>g.replace(h,h.replace(ja,"~"))):e).join("\n")};function ka(a,b,c=!1){return function(d){var f=u(arguments),{stack:e}=Error();const g=t(e,2,!0),h=(e=d instanceof Error)?d.message:d;f=[`Error: ${h}`,...null!==f&&a===f||c?[b]:[g,b]].join("\n");f=w(f);return Object.assign(e?d:Error(),{message:h,stack:f})}};function y(a){var {stack:b}=Error();const c=u(arguments);b=fa(b,a);return ka(c,b,a)};const la=(a,b)=>{b.once("error",c=>{a.emit("error",c)});return b};class ma extends ea{constructor(a){const {binary:b=!1,rs:c=null,...d}=a||{},{F:f=y(!0),proxyError:e}=a||{},g=(h,l)=>f(l);super(d);this.a=[];this.A=new Promise((h,l)=>{this.on("finish",()=>{let k;b?k=Buffer.concat(this.a):k=this.a.join("");h(k);this.a=[]});this.once("error",k=>{if(-1==k.stack.indexOf("\n"))g`${k}`;else{const m=w(k.stack);k.stack=m;e&&g`${k}`}l(k)});c&&la(this,c).pipe(this)})}_write(a,b,c){this.a.push(a);c()}get i(){return this.A}}const z=async a=>{({i:a}=new ma({rs:a,F:y(!0)}));return await a};async function A(a){a=aa(a);return await z(a)};const na=vm.Script;const oa=(a,b)=>{const [c,,d]=a.split("\n");a=parseInt(c.replace(/.+?(\d+)$/,(e,g)=>g))-1;const f=d.indexOf("^");({length:b}=b.split("\n").slice(0,a).join("\n"));return b+f+(a?1:0)};const B=a=>{try{new na(a)}catch(b){const c=b.stack;if(!/Unexpected token '?</.test(b.message))throw b;return oa(c,a)}return null};function C(a){if("object"!=typeof a)return!1;const b=a.re instanceof RegExp;a=-1!=["string","function"].indexOf(typeof a.replacement);return b&&a}const D=(a,b)=>{if(!(b instanceof Error))throw b;[,,a]=a.stack.split("\n",3);a=b.stack.indexOf(a);if(-1==a)throw b;a=b.stack.substr(0,a-1);const c=a.lastIndexOf("\n");b.stack=a.substr(0,c);throw b;};function E(a,b){function c(){return b.filter(C).reduce((d,{re:f,replacement:e})=>{if(this.b)return d;if("string"==typeof e)return d=d.replace(f,e);{let g;return d.replace(f,(h,...l)=>{g=Error();try{return this.b?h:e.call(this,h,...l)}catch(k){D(g,k)}})}},`${a}`)}c.a=()=>{c.b=!0};return c.call(c)};const pa=a=>new RegExp(`%%_RESTREAM_${a.toUpperCase()}_REPLACEMENT_(\\d+)_%%`,"g"),qa=(a,b)=>`%%_RESTREAM_${a.toUpperCase()}_REPLACEMENT_${b}_%%`,F=(a,b)=>Object.keys(a).reduce((c,d)=>{{var f=a[d];const {getReplacement:e=qa,getRegex:g=pa}=b||{},h=g(d);f={name:d,re:f,regExp:h,getReplacement:e,map:{},lastIndex:0}}return{...c,[d]:f}},{}),G=a=>{var b=[];const c=a.map;return{re:a.regExp,replacement(d,f){d=c[f];delete c[f];return E(d,Array.isArray(b)?b:[b])}}},H=a=>{const b=a.map,c=a.getReplacement,d=a.name;
return{re:a.re,replacement(f){const e=a.lastIndex;b[e]=f;a.lastIndex+=1;return c(d,e)}}};async function ra(a,b){return sa(a,b)}
class I extends da{constructor(a,b){super(b);this.a=(Array.isArray(a)?a:[a]).filter(C);this.b=!1;this.i=b}async replace(a,b){const c=new I(this.a,this.i);b&&Object.assign(c,b);a=await ra(c,a);c.b&&(this.b=!0);b&&Object.keys(b).forEach(d=>{b[d]=c[d]});return a}async reduce(a){return await this.a.reduce(async(b,{re:c,replacement:d})=>{b=await b;if(this.b)return b;if("string"==typeof d)b=b.replace(c,d);else{const f=[];let e;const g=b.replace(c,(h,...l)=>{e=Error();try{if(this.b)return f.length?f.push(Promise.resolve(h)):
h;const k=d.call(this,h,...l);k instanceof Promise&&f.push(k);return k}catch(k){D(e,k)}});if(f.length)try{const h=await Promise.all(f);b=b.replace(c,()=>h.shift())}catch(h){D(e,h)}else b=g}return b},`${a}`)}async _transform(a,b,c){try{const d=await this.reduce(a);this.push(d);c()}catch(d){a=w(d.stack),d.stack=a,c(d)}}}async function sa(a,b){b instanceof ca?b.pipe(a):a.end(b);return await z(a)};const ta=a=>{[,a]=/<\s*(.+?)(?:\s+[\s\S]+)?\s*\/?\s*>/.exec(a)||[];return a},K=a=>{let b=0;const c=[];let d;E(a,[{re:/[{}]/g,replacement(l,k){l="}"==l;const m=!l;if(!b&&l)throw Error("A closing } is found without opening one.");b+=m?1:-1;1==b&&m?d={open:k}:0==b&&l&&(d.close=k,c.push(d),d={})}}]);if(b)throw Error(`Unbalanced props (level ${b}) ${a}`);const f={},e=[],g={};var h=c.reduce((l,{open:k,close:m})=>{l=a.slice(l,k);const [,p,n,q,x]=/(\s*)(\S+)(\s*)=(\s*)$/.exec(l)||[];k=a.slice(k+1,m);if(!n&&
!/\s*\.\.\./.test(k))throw Error("Could not detect prop name");n?f[n]=k:e.push(k);g[n]={before:p,s:q,o:x};k=l||"";k=k.slice(0,k.length-(n||"").length-1);const {m:xa,g:ya}=J(k);Object.assign(f,xa);Object.assign(g,ya);return m+1},0);if(c.length){h=a.slice(h);const {m:l,g:k}=J(h);Object.assign(f,l);Object.assign(g,k)}else{const {m:l,g:k}=J(a);Object.assign(f,l);Object.assign(g,k)}return{l:f,j:e,g}},J=a=>{const b=[],c={};a.replace(/(\s*)(\S+)(\s*)=(\s*)(["'])([\s\S]+?)\5/g,(d,f,e,g,h,l,k,m)=>{c[e]={before:f,
s:g,o:h};b.push({h:m,name:e,w:`${l}${k}${l}`});return"%".repeat(d.length)}).replace(/(\s*)([^\s%]+)/g,(d,f,e,g)=>{c[e]={before:f};b.push({h:g,name:e,w:"true"})});return{m:[...b.reduce((d,{h:f,name:e,w:g})=>{d[f]=[e,g];return d},[])].filter(Boolean).reduce((d,[f,e])=>{d[f]=e;return d},{}),g:c}},ua=(a,b=[],c=!1,d={},f="")=>{const e=Object.keys(a);return e.length||b.length?`{${e.reduce((g,h)=>{const l=a[h],k=c||-1!=h.indexOf("-")?`'${h}'`:h,{before:m="",s:p="",o:n=""}=d[h]||{};return[...g,`${m}${k}${p}:${n}${l}`]},
b).join(",")}${f}}`:"{}"},va=(a="")=>{[a]=a;if(!a)throw Error("No tag name is given");return a.toUpperCase()==a},L=(a,b={},c=[],d=[],f=!1,e=null,g={},h="")=>{const l=va(a),k=l?a:`'${a}'`;if(!Object.keys(b).length&&!c.length&&!d.length)return`h(${k})`;const m=l&&"dom"==f?!1:f;l||!d.length||f&&"dom"!=f||e&&e(`JSX: destructuring ${d.join(" ")} is used without quoted props on HTML ${a}.`);a=ua(b,d,m,g,h);b=c.reduce((p,n,q)=>{q=c[q-1];return`${p}${q&&/\S/.test(q)?",":""}${n}`},"");return`h(${k},${a}${b?
`,${b}`:""})`};const M=(a,b=[])=>{let c=0,d;a=E(a,[...b,{re:/[<>]/g,replacement(f,e){if(d)return f;const g="<"==f;c+=g?1:-1;0==c&&!g&&(d=e);return f}}]);if(c)throw Error(1);return{L:a,u:d}},O=a=>{const b=ta(a);let c;const {B:d}=F({B:/=>/g});try{({L:l,u:c}=M(a,[H(d)]))}catch(k){if(1===k)throw Error(`Could not find the matching closing > for ${b}.`);}const f=l.slice(0,c+1);var e=f.replace(/<\s*[^\s/>]+/,"");if(/\/\s*>$/.test(e))return a=e.replace(/\/\s*>$/,""),e="",new N({f:f.replace(d.regExp,"=>"),c:a.replace(d.regExp,
"=>"),content:"",tagName:b});a=e.replace(/>$/,"");e=c+1;c=!1;let g=1,h;E(l,[{re:new RegExp(`[\\s\\S](?:<\\s*${b}(\\s+|>)|/\\s*${b}\\s*>)`,"g"),replacement(k,m,p,n){if(c)return k;m=!m&&k.endsWith(">");const q=!m;if(q){n=n.slice(p);const {u:x}=M(n.replace(/^[\s\S]/," "));n=n.slice(0,x+1);if(/\/\s*>$/.test(n))return k}g+=q?1:-1;0==g&&m&&(c=p,h=c+k.length);return k}}]);if(g)throw Error(`Could not find the matching closing </${b}>.`);e=l.slice(e,c);var l=l.slice(0,h).replace(d.regExp,"=>");return new N({f:l,
c:a.replace(d.regExp,"=>"),content:e.replace(d.regExp,"=>"),tagName:b})};class N{constructor(a){this.f=a.f;this.c=a.c;this.content=a.content;this.tagName=a.tagName}};const P=a=>{let b="",c="";a=a.replace(/^(\r?\n\s*)([\s\S]+)?/,(d,f,e="")=>{b=f;return e}).replace(/([\s\S]+?)?(\r?\n\s*)$/,(d,f="",e="")=>{c=e;return f});return`${b}${a?`\`${a}\``:""}${c}`},za=a=>{const b=[];let c={},d=0,f=0;E(a,[{re:/[<{}]/g,replacement(e,g){if(!(g<f))if(/[{}]/.test(e))d+="{"==e?1:-1,1==d&&void 0==c.from?c.from=g:0==d&&(c.v=g+1,c.G=a.slice(c.from+1,g),b.push(c),c={});else{if(d)return e;e=O(a.slice(g));f=g+e.f.length;c.H=e;c.v=f;c.from=g;b.push(c);c={}}}},{}]);return b.length?wa(a,
b):[P(a)]},wa=(a,b)=>{let c=0;b=b.reduce((d,{from:f,v:e,G:g,H:h})=>{(f=a.slice(c,f))&&d.push(P(f));c=e;g?d.push(g):h&&d.push(h);return d},[]);if(c<a.length){const d=a.slice(c,a.length);d&&b.push(P(d))}return b};const R=(a,b={})=>{var c=b.quoteProps,d=b.warn,f=B(a);if(null===f)return a;var e=a.slice(f);const {c:g="",content:h,tagName:l,f:{length:k}}=O(e);e=Q(h,c,d);const {l:m,j:p,g:n}=K(g.replace(/^ */,""));d=L(l,m,e,p,c,d,n,/\s*$/.exec(g)||[""]);c=a.slice(0,f);a=a.slice(f+k);f=k-d.length;0<f&&(d=`${" ".repeat(f)}${d}`);a=`${c}${d}${a}`;return R(a,b)},Q=(a,b=!1,c=null)=>a?za(a).reduce((d,f)=>{if(f instanceof N){const {c:h="",content:l,tagName:k}=f,{l:m,j:p}=K(h);f=Q(l,b,c);f=L(k,m,f,p,b,c);return[...d,f]}const e=
B(f);if(e){var g=f.slice(e);const {f:{length:h},c:l="",content:k,tagName:m}=O(g),{l:p,j:n}=K(l);g=Q(k,b,c);g=L(m,p,g,n,b,c);const q=f.slice(0,e);f=f.slice(e+h);return[...d,`${q}${g}${f}`]}return[...d,f]},[]):[];const Aa=a=>{const {e:b,C:c,D:d,h:f,I:e,J:g}=F({C:/^ *export\s+default\s+{[\s\S]+?}/mg,e:/^ *export\s+(?:default\s+)?/mg,D:/^ *export\s+{[^}]+}\s+from\s+(['"])(?:.+?)\1/mg,h:/^ *import(\s+([^\s,]+)\s*,?)?(\s*{(?:[^}]+)})?\s+from\s+['"].+['"]/gm,I:/^ *import\s+(?:(.+?)\s*,\s*)?\*\s+as\s+.+?\s+from\s+['"].+['"]/gm,J:/^ *import\s+['"].+['"]/gm},{getReplacement(h,l){return`/*%%_RESTREAM_${h.toUpperCase()}_REPLACEMENT_${l}_%%*/`},getRegex(h){return new RegExp(`/\\*%%_RESTREAM_${h.toUpperCase()}_REPLACEMENT_(\\d+)_%%\\*/`,
"g")}});a=E(a,[H(d),H(c),H(b),H(f),H(e),H(g)]);a=R(a,{});return E(a,[G(d),G(c),G(b),G(f),G(e),G(g)])};async function S(a,b,c){const d=y(!0);if("function"!=typeof a)throw Error("Function must be passed.");if(!a.length)throw Error(`Function${a.name?` ${a.name}`:""} does not accept any arguments.`);return await new Promise((f,e)=>{const g=(l,k)=>l?(l=d(l),e(l)):f(c||k);let h=[g];Array.isArray(b)?h=[...b,g]:1<Array.from(arguments).length&&(h=[b,g]);a(...h)})};const T=async a=>{try{return await S(r,a)}catch(b){return null}};const U=path.dirname,V=path.join,Ba=path.parse,W=path.relative,Ca=path.resolve;const Da=async a=>{var b=await T(a);let c=a,d=!1;if(!b){if(c=await X(a),!c)throw Error(`${a}.js or ${a}.jsx is not found.`);}else if(b.isDirectory()){b=!1;let f;a.endsWith("/")||(f=c=await X(a),b=!0);if(!f){c=await X(V(a,"index"));if(!c)throw Error(`${b?`${a}.jsx? does not exist, and `:""}index.jsx? file is not found in ${a}`);d=!0}}return{path:a.startsWith(".")?W("",c):c,K:d}},X=async a=>{a=`${a}.js`;let b=await T(a);b||(a=`${a}x`);if(b=await T(a))return a};let Y;
const Fa=async(a,b,c={})=>{Y||({root:Y}=Ba(process.cwd()));const {fields:d,soft:f=!1}=c;var e=V(a,"node_modules",b);e=V(e,"package.json");const g=await T(e);if(g){a=await Ea(e,d);if(void 0===a)throw Error(`The package ${W("",e)} does export the module.`);if(!a.entryExists&&!f)throw Error(`The exported module ${a.main} in package ${b} does not exist.`);const {entry:h,version:l,packageName:k,main:m,entryExists:p,...n}=a;return{entry:W("",h),packageJson:W("",e),...l?{version:l}:{},packageName:k,...m?
{hasMain:!0}:{},...p?{}:{entryExists:!1},...n}}if(a==Y&&!g)throw Error(`Package.json for module ${b} not found.`);return Fa(V(Ca(a),".."),b,c)},Ea=async(a,b=[])=>{const c=await A(a);let d,f,e,g,h;try{({module:d,version:f,name:e,main:g,...h}=JSON.parse(c)),h=b.reduce((k,m)=>{k[m]=h[m];return k},{})}catch(k){throw Error(`Could not parse ${a}.`);}a=U(a);b=d||g;if(!b){if(!await T(V(a,"index.js")))return;b=g="index.js"}a=V(a,b);let l;try{({path:l}=await Da(a)),a=l}catch(k){}return{entry:a,version:f,packageName:e,
main:!d&&g,entryExists:!!l,...h}};const Ga=async(a,b,{mount:c,override:d={}})=>{var f=async(e,g,h)=>{var l=U(a);if(/^[/.]/.test(h))return e;{let [p,n,...q]=h.split("/");!p.startsWith("@")&&n?(q=[n,...q],n=p):n=p.startsWith("@")?`${p}/${n}`:p;e={name:n,paths:q.join("/")}}const {name:k,paths:m}=e;if(d[k])return`${g}'${d[k]}'`;({packageJson:l}=await Fa(l,k));e=Ca(l);l=U(e);if(m)return Z(l,m,g,c);({module:e}=require(e));return e?Z(l,e,g,c):(console.warn("[\u219b] Package %s does not specify module in package.json, trying src",l),Z(l,
"src",g))};f=new I([{re:/^( *import(?:\s+[^\s,]+\s*,?)?(?:\s*{(?:[^}]+)})?\s+from\s+)['"](.+)['"]/gm,replacement:f},{re:/^( *import\s+)['"](.+)['"]/gm,replacement:f}]);f.end(b);return await z(f)},Z=(a,b,c,d)=>{a=V(a,b);b=W("",a);d&&(b=W(d,b));return`${c}'/${b}${a.endsWith("/")?"/":""}'`};const Ha=async(a,b,c,{mount:d,override:f})=>{/\.jsx$/.test(a)&&(b=Aa(b),c&&(b=`${c}\n${b}`));return b=/\.css$/.test(a)?`function __$styleInject(css = '') {
  const head = document.head
  const style = document.createElement('style')
  style.type = 'text/css'
  if (style.styleSheet){
    style.styleSheet.cssText = css
  } else {
    style.appendChild(document.createTextNode(css))
  }
  head.appendChild(style)
}
const style = \`${b}\`
__$styleInject(style)`:await Ga(a,b,{mount:d,override:f})};module.exports=function(a={}){const {directory:b="frontend",pragma:c="import { h } from 'preact'",mount:d=".",override:f={}}=a;let {log:e}=a;!0===e&&(e=console.log);const g=Array.isArray(b)?b:[b];g.forEach(h=>{const l=V(d,h);if(!ba(l))throw Error(`Frontend directory ${h} does not exist.`);});return async(h,l)=>{let k=h.path.replace("/","");if(!(g.includes(k)||g.some(x=>k.startsWith(`${x}/`))||h.path.startsWith("/node_modules/")))return await l();k=V(d,k);const {path:m,K:p}=await Da(k);if(p&&!k.endsWith("/"))l=
d?W(d,m):m,h.redirect(`/${l}`);else{try{var n=await S(r,m)}catch(x){h.status=404;return}h.status=200;h.etag=`${n.mtime.getTime()}`;if(h.fresh)return h.status=304,await l();l=await A(m);n=(new Date).getTime();l=await Ha(m,l,c,{mount:d,override:f});var q=(new Date).getTime();e&&e("%s patched in %sms",m,q-n);h.type="application/javascript";h.body=l}}};

//# sourceMappingURL=front-end.js.map