#!/usr/bin/env node
             
const fs = require('fs');
const path = require('path');
const os = require('os');
const stream = require('stream');
const vm = require('vm');
const _crypto = require('crypto');             const aa=fs.createReadStream,ba=fs.existsSync,v=fs.lstat,ca=fs.readFileSync;var da=stream;const ea=stream.Transform,fa=stream.Writable;const ha=(a,b=0,c=!1)=>{if(0===b&&!c)return a;a=a.split("\n",c?b+1:void 0);return c?a[a.length-1]:a.slice(b).join("\n")},ia=(a,b=!1)=>ha(a,2+(b?1:0)),ja=a=>{({callee:{caller:a}}=a);return a};const w=os.EOL,ka=os.homedir;const la=/\s+at.*(?:\(|\s)(.*)\)?/,ma=/^(?:(?:(?:node|(?:internal\/[\w/]*|.*node_modules\/(?:IGNORED_MODULES)\/.*)?\w+)\.js:\d+:\d+)|native)/,na=ka(),x=a=>{const {pretty:b=!1,ignoredModules:c=["pirates"]}={},d=c.join("|"),f=new RegExp(ma.source.replace("IGNORED_MODULES",d));return a.replace(/\\/g,"/").split("\n").filter(e=>{e=e.match(la);if(null===e||!e[1])return!0;e=e[1];return e.includes(".app/Contents/Resources/electron.asar")||e.includes(".app/Contents/Resources/default_app.asar")?!1:!f.test(e)}).filter(e=>
e.trim()).map(e=>b?e.replace(la,(g,h)=>g.replace(h,h.replace(na,"~"))):e).join("\n")};function oa(a,b,c=!1){return function(d){var f=ja(arguments),{stack:e}=Error();const g=ha(e,2,!0),h=(e=d instanceof Error)?d.message:d;f=[`Error: ${h}`,...null!==f&&a===f||c?[b]:[g,b]].join("\n");f=x(f);return Object.assign(e?d:Error(),{message:h,stack:f})}};function y(a){var {stack:b}=Error();const c=ja(arguments);b=ia(b,a);return oa(c,b,a)};const pa=(a,b)=>{b.once("error",c=>{a.emit("error",c)});return b};class qa extends fa{constructor(a){const {binary:b=!1,rs:c=null,...d}=a||{},{M:f=y(!0),proxyError:e}=a||{},g=(h,l)=>f(l);super(d);this.a=[];this.H=new Promise((h,l)=>{this.on("finish",()=>{let k;b?k=Buffer.concat(this.a):k=this.a.join("");h(k);this.a=[]});this.once("error",k=>{if(-1==k.stack.indexOf("\n"))g`${k}`;else{const n=x(k.stack);k.stack=n;e&&g`${k}`}l(k)});c&&pa(this,c).pipe(this)})}_write(a,b,c){this.a.push(a);c()}get o(){return this.H}}const z=async a=>{({o:a}=new qa({rs:a,M:y(!0)}));return await a};async function ra(a){a=aa(a);return await z(a)};const sa=vm.Script;const ta=(a,b)=>{const [c,,d]=a.split("\n");a=parseInt(c.replace(/.+?(\d+)$/,(e,g)=>g))-1;const f=d.indexOf("^");({length:b}=b.split("\n").slice(0,a).join("\n"));return b+f+(a?1:0)};const ua=a=>{try{new sa(a)}catch(b){const c=b.stack;if(!/Unexpected token '?</.test(b.message))throw b;return ta(c,a)}return null};function va(a){if("object"!=typeof a)return!1;const b=a.re instanceof RegExp;a=-1!=["string","function"].indexOf(typeof a.replacement);return b&&a}const A=(a,b)=>{if(!(b instanceof Error))throw b;[,,a]=a.stack.split("\n",3);a=b.stack.indexOf(a);if(-1==a)throw b;a=b.stack.substr(0,a-1);const c=a.lastIndexOf("\n");b.stack=a.substr(0,c);throw b;};function B(a,b){function c(){return b.filter(va).reduce((d,{re:f,replacement:e})=>{if(this.b)return d;if("string"==typeof e)return d=d.replace(f,e);{let g;return d.replace(f,(h,...l)=>{g=Error();try{return this.b?h:e.call(this,h,...l)}catch(k){A(g,k)}})}},`${a}`)}c.a=()=>{c.b=!0};return c.call(c)};const wa=a=>new RegExp(`%%_RESTREAM_${a.toUpperCase()}_REPLACEMENT_(\\d+)_%%`,"g"),xa=(a,b)=>`%%_RESTREAM_${a.toUpperCase()}_REPLACEMENT_${b}_%%`,ya=(a,b)=>Object.keys(a).reduce((c,d)=>{{var f=a[d];const {getReplacement:e=xa,getRegex:g=wa}=b||{},h=g(d);f={name:d,re:f,regExp:h,getReplacement:e,map:{},lastIndex:0}}return{...c,[d]:f}},{}),E=a=>{var b=[];const c=a.map;return{re:a.regExp,replacement(d,f){d=c[f];delete c[f];return B(d,Array.isArray(b)?b:[b])}}},G=a=>{const b=a.map,c=a.getReplacement,d=
a.name;return{re:a.re,replacement(f){const e=a.lastIndex;b[e]=f;a.lastIndex+=1;return c(d,e)}}};async function za(a,b){return Aa(a,b)}
class Ba extends ea{constructor(a,b){super(b);this.a=(Array.isArray(a)?a:[a]).filter(va);this.b=!1;this.o=b}async replace(a,b){const c=new Ba(this.a,this.o);b&&Object.assign(c,b);a=await za(c,a);c.b&&(this.b=!0);b&&Object.keys(b).forEach(d=>{b[d]=c[d]});return a}async reduce(a){return await this.a.reduce(async(b,{re:c,replacement:d})=>{b=await b;if(this.b)return b;if("string"==typeof d)b=b.replace(c,d);else{const f=[];let e;const g=b.replace(c,(h,...l)=>{e=Error();try{if(this.b)return f.length?f.push(Promise.resolve(h)):
h;const k=d.call(this,h,...l);k instanceof Promise&&f.push(k);return k}catch(k){A(e,k)}});if(f.length)try{const h=await Promise.all(f);b=b.replace(c,()=>h.shift())}catch(h){A(e,h)}else b=g}return b},`${a}`)}async _transform(a,b,c){try{const d=await this.reduce(a);this.push(d);c()}catch(d){a=x(d.stack),d.stack=a,c(d)}}}async function Aa(a,b){b instanceof da?b.pipe(a):a.end(b);return await z(a)};const Ca=a=>{[,a]=/<\s*(.+?)(?:\s+[\s\S]+)?\s*\/?\s*>/.exec(a)||[];return a},I=(a,{v:b=!1,classNames:c=[],renameMap:d={}}={})=>{let f=0;const e=[];let g;B(a,[{re:/[{}]/g,replacement(p,m){p="}"==p;const r=!p;if(!f&&p)throw Error("A closing } is found without opening one.");f+=r?1:-1;1==f&&r?g={open:m}:0==f&&p&&(g.close=m,e.push(g),g={})}}]);if(f)throw Error(`Unbalanced props (level ${f}) ${a}`);const h={},l=[],k={};var n=e.reduce((p,{open:m,close:r})=>{p=a.slice(p,m);const [,t,u,C,D]=/(\s*)(\S+)(\s*)=(\s*)$/.exec(p)||
[];m=a.slice(m+1,r);if(!u&&!/\s*\.\.\./.test(m))throw Error("Could not detect prop name");u?h[u]=m:l.push(m);k[u]={before:t,C,B:D};m=p||"";m=m.slice(0,m.length-(u||"").length-1);const {u:L,h:F}=H(m);Object.assign(h,L);Object.assign(k,F);return r+1},0);if(e.length){n=a.slice(n);const {u:p,h:m}=H(n);Object.assign(h,p);Object.assign(k,m)}else{const {u:p,h:m}=H(a);Object.assign(h,p);Object.assign(k,m)}let q=h;if(b||Array.isArray(c)&&c.length||Object.keys(c).length){({...q}=h);const p=[];Object.keys(q).forEach(m=>
{const r=()=>{p.push(m);delete q[m]};if(Array.isArray(c)&&c.includes(m))r();else if(c[m])r();else if(b){const t=m[0];t.toUpperCase()==t&&r()}});p.length&&(n=p.map(m=>m in d?d[m]:m).join(" "),q.className?/[`"']$/.test(q.className)?q.className=q.className.replace(/([`"'])$/,` ${n}$1`):q.className+=`+' ${n}'`:q.g?/[`"']$/.test(q.g)?q.g=q.g.replace(/([`"'])$/,` ${n}$1`):q.g+=`+' ${n}'`:q.className=`'${n}'`)}return{s:q,m:l,h:k}},H=a=>{const b=[],c={};a.replace(/(\s*)(\S+)(\s*)=(\s*)(["'])([\s\S]*?)\5/g,
(d,f,e,g,h,l,k,n)=>{c[e]={before:f,C:g,B:h};b.push({i:n,name:e,G:`${l}${k}${l}`});return"%".repeat(d.length)}).replace(/(\s*)([^\s%]+)/g,(d,f,e,g)=>{c[e]={before:f};b.push({i:g,name:e,G:"true"})});return{u:[...b.reduce((d,{i:f,name:e,G:g})=>{d[f]=[e,g];return d},[])].filter(Boolean).reduce((d,[f,e])=>{d[f]=e;return d},{}),h:c}},Da=(a,b=[],c=!1,d={},f="")=>{const e=Object.keys(a);return e.length||b.length?`{${e.reduce((g,h)=>{const l=a[h],k=c||-1!=h.indexOf("-")?`'${h}'`:h,{before:n="",C:q="",B:p=
""}=d[h]||{};return[...g,`${n}${k}${q}:${p}${l}`]},b).join(",")}${f}}`:"{}"},Ea=(a="")=>{[a]=a;if(!a)throw Error("No tag name is given");return a.toUpperCase()==a},J=(a,b={},c=[],d=[],f=!1,e=null,g={},h="")=>{const l=Ea(a),k=l?a:`'${a}'`;if(!Object.keys(b).length&&!c.length&&!d.length)return`h(${k})`;const n=l&&"dom"==f?!1:f;l||!d.length||f&&"dom"!=f||e&&e(`JSX: destructuring ${d.join(" ")} is used without quoted props on HTML ${a}.`);a=Da(b,d,n,g,h);b=c.reduce((q,p,m)=>{m=c[m-1];let r="";m&&/^\/\*[\s\S]*\*\/$/.test(m)?
r="":m&&/\S/.test(m)&&(r=",");return`${q}${r}${p}`},"");return`h(${k},${a}${b?`,${b}`:""})`};const Fa=(a,b=[])=>{let c=0,d;a=B(a,[...b,{re:/[<>]/g,replacement(f,e){if(d)return f;const g="<"==f;c+=g?1:-1;0==c&&!g&&(d=e);return f}}]);if(c)throw Error(1);return{U:a,D:d}},M=a=>{const b=Ca(a);let c;const {I:d}=ya({I:/=>/g});try{({U:l,D:c}=Fa(a,[G(d)]))}catch(k){if(1===k)throw Error(`Could not find the matching closing > for ${b}.`);}const f=l.slice(0,c+1);var e=f.replace(/<\s*[^\s/>]+/,"");if(/\/\s*>$/.test(e))return a=e.replace(/\/\s*>$/,""),e="",new K({f:f.replace(d.regExp,"=>"),c:a.replace(d.regExp,
"=>"),content:"",tagName:b});a=e.replace(/>$/,"");e=c+1;c=!1;let g=1,h;B(l,[{re:new RegExp(`[\\s\\S](?:<\\s*${b}(\\s+|>)|/\\s*${b}\\s*>)`,"g"),replacement(k,n,q,p){if(c)return k;n=!n&&k.endsWith(">");const m=!n;if(m){p=p.slice(q);const {D:r}=Fa(p.replace(/^[\s\S]/," "));p=p.slice(0,r+1);if(/\/\s*>$/.test(p))return k}g+=m?1:-1;0==g&&n&&(c=q,h=c+k.length);return k}}]);if(g)throw Error(`Could not find the matching closing </${b}>.`);e=l.slice(e,c);var l=l.slice(0,h).replace(d.regExp,"=>");return new K({f:l,
c:a.replace(d.regExp,"=>"),content:e.replace(d.regExp,"=>"),tagName:b})};class K{constructor(a){this.f=a.f;this.c=a.c;this.content=a.content;this.tagName=a.tagName}};const N=a=>{let b="",c="";a=a.replace(/^(\r?\n\s*)([\s\S]+)?/,(d,f,e="")=>{b=f;return e}).replace(/([\s\S]+?)?(\r?\n\s*)$/,(d,f="",e="")=>{c=e;return f});return`${b}${a?`\`${a}\``:""}${c}`},Ha=a=>{const b=[];let c={},d=0,f=0;B(a,[{re:/[<{}]/g,replacement(e,g){if(!(g<f))if(/[{}]/.test(e))d+="{"==e?1:-1,1==d&&void 0==c.from?c.from=g:0==d&&(c.F=g+1,c.N=a.slice(c.from+1,g),b.push(c),c={});else{if(d)return e;e=M(a.slice(g));f=g+e.f.length;c.O=e;c.F=f;c.from=g;b.push(c);c={}}}},{}]);return b.length?Ga(a,
b):[N(a)]},Ga=(a,b)=>{let c=0;b=b.reduce((d,{from:f,F:e,N:g,O:h})=>{(f=a.slice(c,f))&&d.push(N(f));c=e;g?d.push(g):h&&d.push(h);return d},[]);if(c<a.length){const d=a.slice(c,a.length);d&&b.push(N(d))}return b};const Ia=(a,b={})=>{var c=b.quoteProps,d=b.warn;const f=b.prop2class,e=b.classNames,g=b.renameMap;var h=ua(a);if(null===h)return a;var l=a.slice(h);const {c:k="",content:n,tagName:q,f:{length:p}}=M(l);l=O(n,c,d,b);const {s:m,m:r,h:t}=I(k.replace(/^ */,""),{v:f,classNames:e,renameMap:g});d=J(q,m,l,r,c,d,t,/\s*$/.exec(k)||[""]);c=a.slice(0,h);a=a.slice(h+p);h=p-d.length;0<h&&(d=`${" ".repeat(h)}${d}`);a=`${c}${d}${a}`;return Ia(a,b)},O=(a,b=!1,c=null,d={})=>a?Ha(a).reduce((f,e)=>{if(e instanceof K){const {c:l=
"",content:k,tagName:n}=e,{s:q,m:p}=I(l,{v:d.prop2class,classNames:d.classNames,renameMap:d.renameMap});e=O(k,b,c,d);e=J(n,q,e,p,b,c);return[...f,e]}const g=ua(e);if(g){var h=e.slice(g);const {f:{length:l},c:k="",content:n,tagName:q}=M(h),{s:p,m}=I(k,{v:d.prop2class,classNames:d.classNames,renameMap:d.renameMap});h=O(n,b,c,d);h=J(q,p,h,m,b,c);const r=e.slice(0,g);e=e.slice(g+l);return[...f,`${r}${h}${e}`]}return[...f,e]},[]):[];const Ja=(a,b={})=>{const {e:c,K:d,L:f,i:e,P:g,R:h}=ya({K:/^ *export\s+default\s+{[\s\S]+?}/mg,e:/^ *export\s+(?:default\s+)?/mg,L:/^ *export\s+{[^}]+}\s+from\s+(['"])(?:.+?)\1/mg,i:/^ *import(\s+([^\s,]+)\s*,?)?(\s*{(?:[^}]+)})?\s+from\s+['"].+['"]/gm,P:/^ *import\s+(?:(.+?)\s*,\s*)?\*\s+as\s+.+?\s+from\s+['"].+['"]/gm,R:/^ *import\s+['"].+['"]/gm},{getReplacement(l,k){return`/*%%_RESTREAM_${l.toUpperCase()}_REPLACEMENT_${k}_%%*/`},getRegex(l){return new RegExp(`/\\*%%_RESTREAM_${l.toUpperCase()}_REPLACEMENT_(\\d+)_%%\\*/`,
"g")}});a=B(a,[G(f),G(d),G(c),G(e),G(g),G(h)]);b=Ia(a,b);return B(b,[E(f),E(d),E(c),E(e),E(g),E(h)])};async function Ka(a,b,c){const d=y(!0);if("function"!=typeof a)throw Error("Function must be passed.");if(!a.length)throw Error(`Function${a.name?` ${a.name}`:""} does not accept any arguments.`);return await new Promise((f,e)=>{const g=(l,k)=>l?(l=d(l),e(l)):f(c||k);let h=[g];Array.isArray(b)?h=[...b,g]:1<Array.from(arguments).length&&(h=[b,g]);a(...h)})};const P=async a=>{try{return await Ka(v,a)}catch(b){return null}};const La=path.basename,Q=path.dirname,R=path.join,Ma=path.parse,S=path.relative,Na=path.resolve;const Oa=async a=>{var b=await P(a);let c=a,d=!1;if(!b){if(c=await T(a),!c)throw Error(`${a}.js or ${a}.jsx is not found.`);}else if(b.isDirectory()){b=!1;let f;a.endsWith("/")||(f=c=await T(a),b=!0);if(!f){c=await T(R(a,"index"));if(!c)throw Error(`${b?`${a}.jsx? does not exist, and `:""}index.jsx? file is not found in ${a}`);d=!0}}return{path:a.startsWith(".")?S("",c):c,S:d}},T=async a=>{a=`${a}.js`;let b=await P(a);b||(a=`${a}x`);if(b=await P(a))return a};function U(a,b,c){const d=[];b.replace(a,(f,...e)=>{f=e.slice(0,e.length-2).reduce((g,h,l)=>{l=c[l];if(!l||void 0===h)return g;g[l]=h;return g},{});d.push(f)});return d};/*
 diff package https://github.com/kpdecker/jsdiff
 BSD License
 Copyright (c) 2009-2015, Kevin Decker <kpdecker@gmail.com>
*/
const Pa={black:30,red:31,green:32,yellow:33,blue:34,magenta:35,cyan:36,white:37,grey:90},Qa={black:40,red:41,green:42,yellow:43,blue:44,magenta:45,cyan:46,white:47};function Ra(a,b){return(b=Pa[b])?`\x1b[${b}m${a}\x1b[0m`:a}function Sa(a,b){return(b=Qa[b])?`\x1b[${b}m${a}\x1b[0m`:a};const Ta=_crypto.createHash;function Ua(a){a=JSON.stringify(a);const b=Buffer.byteLength(a),c=126>b?0:2;var d=0===c?b:126;const f=Buffer.alloc(2+c+b);f.writeUInt8(129,0);f.writeUInt8(d,1);d=2;0<c&&(f.writeUInt16BE(b,2),d+=c);f.write(a,d);return f}function Va(a){return Ta("sha1").update(`${a}258EAFA5-E914-47DA-95CA-C5AB0DC85B11`,"binary").digest("base64")};function Wa(a){const {onMessage:b=()=>{},onConnect:c=()=>{},log:d=!0}={},f={};a.on("upgrade",function(e,g){if("websocket"!=e.headers.upgrade)g.end("HTTP/1.1 400 Bad Request");else{var h=e.headers["sec-websocket-protocol"],l=e.headers["sec-websocket-key"];e=["HTTP/1.1 101 Web Socket Protocol Handshake","Upgrade: WebSocket","Connection: Upgrade",`Sec-WebSocket-Accept: ${Va(l)}`];(h?h.split(",").map(k=>k.trim()):[]).includes("json")&&e.push("Sec-WebSocket-Protocol: json");g.write(e.join("\r\n")+"\r\n\r\n");
d&&console.log(Sa("Client connected.","green"));g.on("data",k=>{var n=k.readUInt8(0)&15;if(8===n)k=null;else if(1===n){var q=k.readUInt8(1),p=!!(q>>>7&1);n=2;q&=127;if(125<q)if(126===q)q=k.readUInt16BE(n),n+=2;else throw k.readUInt32BE(n),k.readUInt32BE(n+4),Error("Large payloads not currently implemented");if(p){var m=k.readUInt32BE(n);n+=4}var r=Buffer.alloc(q);if(p)for(let t=0,u=0;t<q;++t,u=t%4){p=3==u?0:3-u<<3;p=(0==p?m:m>>>p)&255;const C=k.readUInt8(n++);r.writeUInt8(p^C,t)}else k.copy(r,0,n++);
k=`${r}`}else k=void 0;k?b(l,k):null===k&&(delete f[l],d&&console.log(Sa("Client disconnected.","red")))});f[l]=(k,n)=>{g.write(Ua({event:k,message:n}))};c(l)}});return f};let V;
const Ya=async(a,b,c={})=>{V||({root:V}=Ma(process.cwd()));const {fields:d,soft:f=!1}=c;var e=R(a,"node_modules",b);e=R(e,"package.json");const g=await P(e);if(g){a=await Xa(e,d);if(void 0===a)throw Error(`The package ${S("",e)} does export the module.`);if(!a.entryExists&&!f)throw Error(`The exported module ${a.main} in package ${b} does not exist.`);const {entry:h,version:l,packageName:k,main:n,entryExists:q,...p}=a;return{entry:S("",h),packageJson:S("",e),...l?{version:l}:{},packageName:k,...n?
{hasMain:!0}:{},...q?{}:{entryExists:!1},...p}}if(a==V&&!g)throw Error(`Package.json for module ${b} not found.`);return Ya(R(Na(a),".."),b,c)},Xa=async(a,b=[])=>{const c=await ra(a);let d,f,e,g,h;try{({module:d,version:f,name:e,main:g,...h}=JSON.parse(c)),h=b.reduce((k,n)=>{k[n]=h[n];return k},{})}catch(k){throw Error(`Could not parse ${a}.`);}a=Q(a);b=d||g;if(!b){if(!await P(R(a,"index.js")))return;b=g="index.js"}a=R(a,b);let l;try{({path:l}=await Oa(a)),a=l}catch(k){}return{entry:a,version:f,packageName:e,
main:!d&&g,entryExists:!!l,...h}};const Za=async(a,b,{mount:c,override:d={}})=>{var f=async(e,g,h)=>{var l=Q(a);if(/^[/.]/.test(h))return e;{let [q,p,...m]=h.split("/");!q.startsWith("@")&&p?(m=[p,...m],p=q):p=q.startsWith("@")?`${q}/${p}`:q;e={name:p,paths:m.join("/")}}const {name:k,paths:n}=e;if(d[k])return`${g}'${d[k]}'`;({packageJson:l}=await Ya(l,k));e=Na(l);l=Q(e);if(n)return W(l,n,g,c);({module:e}=require(e));return e?W(l,e,g,c):(console.warn("[\u219b] Package %s does not specify module in package.json, trying src",l),W(l,
"src",g))};f=new Ba([{re:/^( *import(?:\s+[^\s,]+\s*,?)?(?:\s*{(?:[^}]+)})?\s+from\s+)['"](.+)['"]/gm,replacement:f},{re:/^( *import\s+)['"](.+)['"]/gm,replacement:f}]);f.end(b);return await z(f)},W=(a,b,c,d)=>{a=R(a,b);b=S("",a);d&&(b=S(d,b));return`${c}'/${b}${/[/\\]$/.test(a)?"/":""}'`.replace(/\\/g,"/")};function $a(a=""){let b;window["FRONTEND-STYLE-ID"]?(b=window["FRONTEND-STYLE-ID"],b.innerText=""):(b=document.createElement("style"),b.id="FRONTEND-STYLE-ID",document.head.appendChild(b));b.type="text/css";b.styleSheet?b.styleSheet.cssText=a:b.appendChild(document.createTextNode(a))};const ab=a=>{const b=U(/^export\s+(default\s+)?class\s+([^\s{]+)/gm,a,["def","name"]).reduce((g,{def:h,name:l})=>{if("extends"==l)return g;g[h?"default":l]=l;return g},{}),c=U(/^class\s+([^\s{]+)/gm,a,["name"]).map(({name:g})=>g).filter(g=>"extends"!=g),d=U(/^export\s+{([^}]+)}/gm,a,["exp"]).reduce((g,{exp:h})=>[...g,...h.split(/\s+/).filter(Boolean)],[]),{l:f,j:e}=d.reduce(({j:g,l:h},l)=>{c.includes(l)?h.push(l):g.push(l);return{j:g,l:h}},{j:[],l:[]});f.forEach(g=>b[g]=g);a=U(/^export\s+default\s+(\S+)/gm,
a,["name"]).map(({name:g})=>g).filter(g=>c.includes(g));[a]=a;a&&(b["default"]=a);return{J:b,T:e}},bb=a=>U(/^export\s+(const|let)\s+(\S+)\s+=/gm,a,["type","name"]).reduce((b,{name:c})=>{b[c]=c;return b},{}),cb=(a,b,c,d=null)=>{b=Object.entries(b).map(([f,e])=>`'${f}': ${e},`);return`/* IDIO HOT RELOAD */
${d?`import { idioHotReload } from '${d}'`:"const idioHotReload = window.idioHotReload"}
if (idioHotReload) {
  let _idio = 0
  idioHotReload('${a}', async () => {
    _idio++
    const module = await import(\`./${La(a).replace(/\.jsx?$/,"")}?ihr=\${_idio}\`)
${Object.keys(c).map(f=>`    ${f} = module['${f}']`).join("\n")}
    return {
      module,${b.length?`
      classes: {
${b.map(f=>`        ${f}`).join(w)}
      },`:""}
    }
  })
}`.replace(/\r?\n/g,w)};let X,db,Y,Z;
const eb=(a,b,c,d)=>{var f=c.ignoreNodeModules,e=c.module;c=c.path;if(a.startsWith("node_modules")&&f)return b;const g=Ra("[@idio/frontend]","grey");try{X||(X=require("node-watch"))}catch(n){console.error("%s node-watch is recommended for front-end hot reload.",g),console.error("%s Falling back to standard watch.",g),db=!0,X=require("fs").watch}a in d.A||(f=X(a,(n,q)=>{console.error("%s File %s changed",g,Ra(q,"yellow"));Object.values(d.w).forEach(p=>{p("update",{filename:db?a:q})})}),d.A[a]=f);const {J:h,
T:l=[]}=ab(b),k=bb(b);l.forEach(n=>{k[n]=n});e=cb(a,h,k,e?c:null);b=b.replace(/^export(\s+)const(\s+)(\S+)\s+=/gm,n=>n.replace("const","let"));l.length&&(b=b.replace(new RegExp(`^const(\\s+(?:${l.join("|")})\\s+)`,"gm"),"let$1"));return b+=`${w}${w}${e}`},gb=async(a,b,c,d)=>{const f=d.jsxOptions,e=d.exportClasses;/\.jsx$/.test(a)&&(b=Ja(b,f),c&&(b=`${c}${w}${b}`));return b=/\.css$/.test(a)?fb(b,{exportClasses:e,path:a}):await Za(a,b,d)},fb=(a,{exportClasses:b=!0,path:c=""}={})=>{var d=[];b&&(d=a.split(/\r?\n/).filter(f=>
/^\S/.test(f)).join(w),d=U(/\.([\w\d_-]+)/g,d,["className"]).map(({className:f})=>f).filter((f,e,g)=>g.indexOf(f)==e));c=c.replace(/\.css$/,"").replace(/[/\\]/g,"-").replace(/[^\w\d_-]/g,"");return`(${$a.toString().replace(/FRONTEND-STYLE-ID/g,c)})(\`${a}\`)
${d.map(f=>`export const $${f} = '${f}'`).join(w)}`.replace(/\r?\n/g,w).trim()};module.exports=function(a={}){const {directory:b="frontend",pragma:c="import { h } from 'preact'",mount:d=".",jsxOptions:f,exportClasses:e=!0,hotReload:g}=a;let {log:h,override:l={}}=a;!0===h&&(h=console.log);let k=Array.isArray(b)?b:[b];k=k.map(m=>{const r=R(d,m);if(!ba(r))throw Error(`Frontend directory ${m} does not exist.`);return m.replace(/\\/g,"/")});let n={},q;g&&(g.path||(g.path="/hot-reload"),"module"in g||(g.module=!0),"ignoreNodeModules"in g||(g.ignoreNodeModules=!0),{watchers:a={}}=g,
n.A=a,n.w={},l={...l,"@idio/hot-reload":g.path},a=g.path,q=[a,a.replace(/\.jsx?$/,"")].filter((m,r,t)=>t.indexOf(m)==r));let p=!1;return async(m,r)=>{if(g&&q.includes(m.path))m.type="js",g.module&&!Z?Z=ca(R(__dirname,"listener.mjs")):g.module||Y||(Y=ca(R(__dirname,"listener.js"))),m.body=g.module?Z:Y,p||(m=g.getServer(),n.w=Wa(m),p=!0);else{var t=m.path.replace("/","");if(!(k.includes(t)||k.some(F=>t.startsWith(`${F}/`))||m.path.startsWith("/node_modules/")))return r();t=R(d,t).replace(/\\/g,"/");
var {path:u,S:C}=await Oa(t);if(C&&!t.endsWith("/"))r=d?S(d,u).replace(/\\/g,"/"):u,m.redirect(`/${r}`);else{try{var D=await Ka(v,u)}catch(F){m.status=404;return}m.status=200;m.etag=`${D.mtime.getTime()}`;if(m.fresh)return m.status=304,r();r=await ra(u);D=(new Date).getTime();r=await gb(u,r,c,{mount:d,override:l,jsxOptions:f,exportClasses:e});var L=(new Date).getTime();h&&h("%s patched in %sms",u,L-D);m.type="application/javascript";g&&!m.query.V&&(r=eb(u,r,g,n));m.body=r}}}};

//# sourceMappingURL=front-end.js.map