name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.platform }}

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
        platform: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - run: yarn test
    - run: yarn test-compile